### ISSUE TITLE
Aggregate report on multi-module-project

### ISSUE THREAD

**Issue by brianpreuss** [jk1/Gradle-License-Report#10]
Hi,

is it possible to generate an aggregate report for a multi-module-project?

Regards,

Brian

**Comment by jk1** [comment]
Hello,

It is, although not immediate obvious. Here's how it can work:

1. Project A, that exports it's dependency report into xml and exposes this xml as gradle artifact
2. Project B, that depends on A and imports it's report via XmlReportImporter and merges with it's own

**Comment by dmoebius** [comment]
Would be great if the plugin would perform this merging automatically for a multi-module project.

**Comment by damianoneill** [comment]
+1

**Comment by margelatu** [comment]
+1

**Comment by ManfredSchenkIOSB** [comment]
+1

**Comment by xellsys** [comment]
You should be able to associate the dependency to the sub project though. Otherwise in big multi project builds, you have to search for it manually.
I'm not sure if the current model allows for that though.

**Comment by guenhter** [comment]
Just thinking out loud here, but what if the current model stays untouched and a `ProjectData` is created for each sub-project. Then this list of `ProjectData`'s can then be passed to the `filters`/`renderers`. That also implies, that we would break the interfaces and therefore compatibility (if the existing renderers are exteded). Or new renderers are created, which can handle the List of `ProjectData`.  To avoid that one lincense (e.g. commons-lang) appears twenty times, the renderer should be configurable if projects should be rendered independently, or if all the `ProjectData` objects are merged.
This might be quite easy to implement.
Any thoughts on this?

**Comment by jk1** [comment]
Not sure if this idea will work with the configuration on demand option enabled.
Other than that this approach looks promising.

**Comment by catellie** [comment]
@guenhter This sounds great to me. Have you tried this idea yet?

**Comment by guenhter** [comment]
Not yet. I'll try that, after my other issues are resolved. So may be in a few weeks...

**Comment by catellie** [comment]
Actually, after fiddling with the setup it appears that the current implementation is good enough for my particular case: My project has two modules where one (a) of them refers to the other (b), so by running the report on the primary module (a) only appears to produce the summary I'm after.
Great stuff, keep it up!

**Comment by jk1** [comment]
> so by running the report on the primary module (a) only appears to produce the summary I'm after.

This is true for many other use cases. The thing is, one often needs a report to accompany a distribution of some sort (jar, war, ear). Since this distribution is built with all necessary sibling projects declared as dependencies the desired report can be built for this distribution module only. Just make sure all cross-module dependencies in your project are declared as such.

Nevertheless, basic multi-project support has been implemented by @guenhter and has been shipped in 0.9.

**Comment by guenhter** [comment]
Is this still relevant?

**Comment by jk1** [comment]
I believe we can consider it fixed.
