### ISSUE TITLE
Add text from additional file to Json

### ISSUE THREAD

**Issue by JohannesPtaszyk** [jk1/Gradle-License-Report#101]
It would be really nice, if we could have functionality to insert the "Notice.txt" and license files text into a Json field, so it gets easy to just parse the Json and get the text from there.

What do you think about that?

**Comment by guenhter** [comment]
Hi, I don't quite get your request. Which Json are you talking about and were do you want to access then the content? Can you elaborate on this a little bit more.

**Comment by JohannesPtaszyk** [comment]
So, sometimes in a dependencies package there are files like "license.md" or "license" or files named "notice.txt". In my opinion it woul be great to get the content of these files in the json which is generated by the jsonrenderer. 

I dont quite get how the package parsing process works, otherwise I would contribute, but meh, not really getting it.

**Comment by guenhter** [comment]
Mhm, interesting. Should the whole text be added, or is a link to the actual file (which is already extracted and stored on the filesystem) enough?

**Comment by JohannesPtaszyk** [comment]
Sorry, for taking that long to answer. I would like to see the whole text to be added to the json, so I can then show it to the user quite easily.

**Comment by jk1** [comment]
I believe this is exactly what custom renderer support is implemented for.
Please refer to the readme file on how to implement your own renderer.
