### ISSUE TITLE
 JsonReportRenderer Bug?

### ISSUE THREAD

**Issue by knuthie** [jk1/Gradle-License-Report#102]
Hi,
I think there is a bug in the JsonReportRenderer.groovy. 
If one uses customer importers, only the last module entry is included in the Json output and not all.

Problem seems to me the method:
 static def readModuleDependencies(def modules) 
I think it should call  
**modules.collect**
and not
**modules.collectEntries**
(The contents of modules is a treeset of ImportedModuleData, not a map)
(or is my importer wrong?)

**Comment by jk1** [comment]
Hi,

You're absolutely right about that, JsonReportRenderer is to blame here.
Thanks for reporting the problem.
