### ISSUE TITLE
Dependencies with the same group as project are excluded from the report

### ISSUE THREAD

**Issue by SpencerPark** [jk1/Gradle-License-Report#103]
As of 1.2 I'm having the issue that when I depend on my own modules (_not_ a subproject, an external one) with the same group name it gets ignored in the report. Excluding the project group is not an option because I would like it in the report as it is an external dependency. It happens to share the same group name but is not part of the project.

I believe this is related to a fix mentioned in #85. I don't mind staying on 1.1 as I've yet to have any problems but this is preventing me from updating.

**Comment by guenhter** [comment]
I guess the only really reliable fix would be to check if a dependency is a project dependency or a (maven) library dependency, but off the top of my head I don't know how to check that...

**Comment by SpencerPark** [comment]
Is it possible to compare more than just the group (name and maybe even version as well)? The list of projects and subprojects should be known in advance even it it doesn't match the `projects` in the license extension.

**Comment by jk1** [comment]
Not sure if it's worth trying to be very smart here. I've added a dedicated configuration option instead, `excludeOwnGroup`.  It seems that a combination of `excludeOwnGroup`, `exclude` and `excludeGroup` can cover almost every possible scenario.

**Comment by SpencerPark** [comment]
Thanks @jk1! I agree, and I think the ability to toggle `excludeOwnGroup` is what I needed.

**Comment by jk1** [comment]
@SpencerPark just for the reference, it will arrive in 0.17
