### ISSUE TITLE
RFE: Add support for Java Library plugin

### ISSUE THREAD

**Issue by basil** [jk1/Gradle-License-Report#104]
I recently started using the License Report plugin in two Gradle builds: one that uses [the Java plugin](https://docs.gradle.org/current/userguide/java_plugin.html), and one that uses [the Java Library plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html). With the former, the Gradle License Report plugin worked out of the box. With the latter, many of my third-party libraries were not properly detected and included in the license report. It would be nice if the Gradle License Report plugin automatically supported the Java Library plugin out of the box.

As a workaround, I directed the License Report plugin to the configuration preferred by the Java Library plugin:

```
licenseReport {
    /*
     * The License Report plugin defaults to the 'runtime' configuration; however, we use the Java
     * Library Plugin plugin rather than the Java Plugin, and the Java Library Plugin has deprecated
     * the 'runtime' configuration in favor of the 'runtimeClasspath' configuration. If we use the
     * deprecated 'runtime' configuration, many dependencies are missing from the final report.
     * Therefore, we use the non-deprecated 'runtimeClasspath' configuration so that we obtain all
     * the required dependencies.
     */
    configurations = ['runtimeClasspath']
}
```

**Comment by jk1** [comment]
And indeed, there is in fact a statement from Gradle developers about the deprecation: https://discuss.gradle.org/t/when-should-we-use-java-plugin-and-when-java-library-plugin/25377/2

To stay compatible we may detect that Java Library Plugin is present and use a different default configuration in that case.
