### ISSUE TITLE
excludeGroups seems to only exclude the jars, but not the entry in the report

### ISSUE THREAD

**Issue by alebo611** [jk1/Gradle-License-Report#106]
As the title says, using excludeGroups = ['exclude.this'] will still show exclude.this in the report (but the jar will not be copied to the folder).

**Comment by guenhter** [comment]
I just tried to exclude a library (group `com.couchbase.client`) and it worked. The entry is not longer in the HTML-Report. Can you provide some details to reproduce the problem?

**Comment by alebo611** [comment]
Im using gradle 4.3.1 with gradle-license-report version 1.3. Maybe thats a bad match.

**Comment by alebo611** [comment]
Tried it with latest version, still no difference. Im using a root-subproject build setup where my dependencies are specified through own configurations. 

```
In common.gradle:
    common_ext_lib (
        [group: 'org.hsqldb', name: 'hsqldb', version: '2.4.0'],
        [group: 'org.hsqldb', name: 'sqltool', version: '2.4.0'],
        [group: 'jaxb-plugins', name: 'jaxb-plugins', version: '1'],
      . . .
)
```

And in subprojects I do this:
```
dependencies {
   compile configurations.common_ext_lib
}
```

**Comment by guenhter** [comment]
I just tried this out with latest version of gradle and with 4.3.1. Maybe we are not quite on the same page.
Here is my full `build.gradle`. When I execute the report with `./gradlew clean generateLicenseReport` the file `build/reports/dependency-license/index.html` is generated. When I look at it, nothing of `ch.qos.logback` is contained. And in your case, the `excludedGroups` still shows up in the report, is this correct?

```
import com.github.jk1.license.LicenseReportPlugin
import com.github.jk1.license.render.InventoryHtmlReportRenderer

plugins {
  id "com.github.jk1.dependency-license-report" version "1.3"
}

apply plugin: 'java-library'

repositories {
    mavenCentral()
}

dependencies {
    implementation('ch.qos.logback:logback-classic:1.2.3')
}

licenseReport {
    renderers = [new InventoryHtmlReportRenderer()]
    configurations = ['runtimeClasspath']
    excludeGroups = ['ch.qos.logback']
}
```

**Comment by alebo611** [comment]
(Which gradle version do you mean by "latest"?)
Yes, I I try the following, logback is still presented My configuration looks only like this:
```
licenseReport {
    outputDir = "$projectDir/build/licenses"
      excludeGroups = ['ch.qos.logback']
    renderers = [new TextReportRenderer()]
    projects = [project] + project.subprojects
    configurations = ['ALL']
}
```

**Comment by guenhter** [comment]
I tried with 4.10.2

Really interesting ... do you apply the plugin only on the root project or on all sub projects?

**Comment by alebo611** [comment]
Only in root project. But now I see I have 

```
plugins {  
    id "com.github.jk1.dependency-license-report" version "1.2"
}
```
in root build.gradle and
`apply plugin: 'com.github.jk1.dependency-license-report'`
in common.gradle. Is this a wrong setup?

**Comment by guenhter** [comment]
Now we start to narrow down the problem.
So you have the plugin installed twice:
* once in the root project
* and once in the `common.gradle`

I guess you have the configuration ( `licenseReport { .... }`) also in the  `common.gradle`, do you?

---

It is usually no problem to apply the plugin twice on different projects, but you also have to keep in mind to configure the two plugins then independently. So to test this out, try to put the plugin installation (`apply`) and the plugin configuration into the root project. 

---

It depends on your use case if you should apply the plugin several times:
* If you want one report over all subproject: Apply the plugin on only on the root project
* If you want separate reports for each subproject: Apply the plugin on all subprojects

**Comment by alebo611** [comment]
The apply in common.gradle was the problem. licenseReport was in root build.gradle. I moved the apply to the root build.gradle (I want one report over all subproject). Thank you for taking you time to help. You can close this issue now.
