### ISSUE TITLE
Feature comparison to Google's Open Source Notice plugin?

### ISSUE THREAD

**Issue by alixwar** [jk1/Gradle-License-Report#108]
Google has a plugin that pretty much solves the same problem for Android (reporting Open Source libraries used): https://developers.google.com/android/guides/opensource

Limitations, in that plugin, that I've stumbled on:
- No configuration on report format (assumes you want to display it in an activity which the plugin provides)
- Does not include project submodule licenses
- No way of filtering the list (it includes stuff like kotlin-plugins used in the build)

It would be good to have a feature matrix that compares this project with Googles

**Comment by jk1** [comment]
It would, but it requires some experience with both. I will gladly accept a pull request with such a matrix.

From what I can tell from its source code Google plugin requires less configuration for Android projects.
Gradle-License-Report, in turn, is capable of finding more licenses, provides more means of configuration and extension.
