### ISSUE TITLE
Kotlin support example appears to be incorrect

### ISSUE THREAD

**Issue by vpavic** [jk1/Gradle-License-Report#124]
I'm migrating a project that uses this plugin to Kotlin DSL, and [example in project's readme](https://github.com/jk1/Gradle-License-Report#kotlin-script-support) doesn't appear to be working.

Namely, the following configuration:

```kotlin
licenseReport {
    renderers = arrayOf(CsvReportRenderer(), InventoryHtmlReportRenderer())
}
```

Results in the following error:
```
[Ljava.lang.Object; cannot be cast to [Lcom.github.jk1.license.render.ReportRenderer;
```

The syntax that works for me is:

```kotlin
licenseReport {
    renderers = arrayOf<ReportRenderer>(CsvReportRenderer(), InventoryHtmlReportRenderer())
}
```

This is with latest `1.4` release of the plugin, and Gradle `5.1.1`.

**Comment by guenhter** [comment]
Hm, I guess you're right. I mean the example in the Readme is actually not wrong, but just works then for one single Renderer. As soon as you add a second one, you're right. This should also be adapted in the sample project.
Thx

**Comment by jk1** [comment]
Good catch, thank you.
I have changed the example accordingly.
