### ISSUE TITLE
Support dependencies with 'implementation'

### ISSUE THREAD

**Issue by jaecktec** [jk1/Gradle-License-Report#125]
We need to create a dependency report for a spring-boot application. We are currently using gradle 4.10.

Resolving the dependencies works, when we use 'compile(...)' to include our dependencies. However the newer feature 'implementation(...)' does not work. 

We've tried the solution mentioned in #47 without success.

Is this a known issue or a work around for this?

Thanks a lot!

**Comment by jk1** [comment]
The solution is to specify the configuration specific to your build environment for the plugin to gather dependencies from. My knowledge of spring-boot build features are not that deep to tell what configuration it is.

Is it possible for you to provide a minimal self-contained build script, that demonstrates the problem?

**Comment by jaecktec** [comment]
I have adjusted a spring init project 

https://github.com/jaecktec/spring-license-report-demo

**Comment by jaecktec** [comment]
Any suggestions here?

**Comment by jk1** [comment]
I'll be able to look into it over the weekend

**Comment by jk1** [comment]
It seems that the proper configuration for your use case is this:

```
configurations = ['runtimeClasspath']
```

This is not an issue of the license report plugin, but rather a configuration issue in your build. Spring boot plugin uses its own configurations layout to store build dependencies ignoring the defaults provided by gradle java plugin. `configurations` parameter is designed to adopt the license report plugin to an arbitrary customized build layouts, such as yours.

Btw, one can always discover all build configurations available by running `./gradlew dependencies` command.

**Comment by jaecktec** [comment]
Thanks for your support! :)
