### ISSUE TITLE
Unable to match stax-ex license by URL

### ISSUE THREAD

**Issue by cowwoc** [jk1/Gradle-License-Report#131]
Version 1.5

Looking at https://github.com/javaee/metro-stax-ex/blob/master/stax-ex/pom.xml

I am unable to match the license by URL:
```
    {
      "bundleName": "cddl+gpl1.1",
      "licenseUrlPattern": "https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html"
    },
```

but matching by name works fine:
```
    {
      "bundleName": "cddl+gpl1.1",
      "licenseNamePattern": "(?s).*Dual license consisting of the CDDL v1.1 and GPL v2.*"
    }
```

I don't like matching by name because it is error-prone. Any idea why matching by URL is not working?

**Comment by jk1** [comment]
I would escape plus sign in the pattern:
`https://glassfish.dev.java.net/public/CDDL\\+GPL_1_1.html`

**Comment by guenhter** [comment]
This is the groovy code which is used to check for a matching pattern.
```
it.licenseUrlPattern && url ==~ it.licenseUrlPattern
```

Maybe we should think about check the URL with plain text for equality first, and if that check fails, doing a REGEX match. What do you guys think of that?

**Comment by cowwoc** [comment]
@guenhter I think that would actually cause more confusion (matching when it shouldn't). In this case, I think it would have helped to log "Trying to match URL: X [...] X does not match regex Y."

I was so convinced that the code wasn't even trying to match the two strings that it didn't occur to me to debug this using an online service like https://regex101.com/

I *did* use this service for other configuration items, but it didn't occur to me that this could be a legitimate bug in the regex.

The second thing that hurt me is I couldn't figure out how to debug the plugin in IntelliJ IDEA. The plugin's `import` statements and `new LicenseBundleNormalizer` lines were showing up in red. I still haven't figured out how to resolve this, but if I had been able to step through the code I would have figured this out.

**Comment by cowwoc** [comment]
@jk1 Thanks for catching the problem with the regex. Sorry for the false alarm.

**Comment by cowwoc** [comment]
@jk1 Interesting... this issue isn't fixed.

According to https://regex101.com/ the regex `.*\/CDDL\+GPL_1_1\.html` should match URL `https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html` and yet when I try this the plugin isn't matching the stax-ex license. Can you please try reproducing this problem on your end?

I'd love to be able to step through the code on my end through IDEA :) This would certainly speed things up.

**Comment by jk1** [comment]
Adding a bit of logging is almost never a bad idea. It wouldn't have told you anything besides the text not matching the rule though. And this is something you knew already. 

A suggestion by @guenhter makes total sense to me though. People are looking for an exact match most of the time. Speaking about false positives, it's hard to imagine license URL or name to contain a typical regex syntax construct.

**Comment by cowwoc** [comment]
@jk1 If you're keen on going this way, perhaps use `licenseUrl` for literal interpretation and keep `licenseUrlPattern` as is.

**Comment by jk1** [comment]
@cowwoc the problem is, `licenseNamePattern` is doing an exact comparison already before trying the regexp match.
