### ISSUE TITLE
Accept both License or Licence spelling

### ISSUE THREAD

**Issue by cowwoc** [jk1/Gradle-License-Report#134]
Here is an updated name pattern for https://github.com/jk1/Gradle-License-Report/blob/master/src/main/resources/default-license-normalizer-bundle.json#L64:

```
    {
      "bundleName": "mit",
      "licenseNamePattern": "(The\\s)?MIT(\\s[l|L]icen[c|s]e)?"
    }
```

Change: Accept both `license` and `licence` spelling.

**Comment by jk1** [comment]
Thanks for the suggestion, please find it merged.
