### ISSUE TITLE
De-fork repository

### ISSUE THREAD

**Issue by stuartraetaylor** [jk1/Gradle-License-Report#137]
Would there be any interest in de-forking this project (to be standalone and not a fork) so that it becomes more visible on GitHub? For example, I can't find the repository in the search or see any contributions.

I think it would be reasonable to remove the fork relationship since the project no longer resembles the original and is unlikely to ever be pulled in.

What do we think?

https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

Cheers,
Stuart.

**Comment by jk1** [comment]
Hi Stuart,

That would be a logical thing to do. Your suggestion is much appreciated.
I'll contact GitHub support to get the repo deforked.

**Comment by jk1** [comment]
Done
