### ISSUE TITLE
ReportRenderer API looks awkward: LicenseDataCollector uses protected visibility

### ISSUE THREAD

**Issue by vlsi** [jk1/Gradle-License-Report#139]
The methods of `LicenseDataCollector` are `protected` thus it is effectively impossible to use in third-party code: https://github.com/jk1/Gradle-License-Report/blob/f167c2bdb622d239a296ea2b3f446cbd8e23be70/src/main/groovy/com/github/jk1/license/render/LicenseDataCollector.groovy#L24

Should this API be public?
What's the purpose of extending `LicenseDataCollector`?

**Comment by jk1** [comment]
> What's the purpose of extending LicenseDataCollector?

There's none I believe.
Let us make the API public.
