### ISSUE TITLE
ReportTask does not honour LicenseReportExtension#projects

### ISSUE THREAD

**Issue by vlsi** [jk1/Gradle-License-Report#141]
`ReportTask` uses `getProject().subprojects + getProject()`, however the set of projects is declared in `LicenseReportExtension#projects`.

This leads to invalid value for `@InputFiles FileCollection getClasspath()`, thus invalid caching behavior of the task.

**Comment by jk1** [comment]
Thank you for reporting this.
`LicenseReportExtension#getLicenseReportExtensionSnapshot` seems to force the correct behavior in some cases though.
