### ISSUE TITLE
Wrong module versions for (second-level-)transitive dependencies

### ISSUE THREAD

**Issue by sebastiankutschbach** [jk1/Gradle-License-Report#151]
When I generate a license report for a spring boot project, I get a list containing a list of transitive and non-transitive dependencies. Some of the transitive dependencies are containing transitive dependencies as well.

The module version for the first level of transitive dependencies seems to be valid, starting from the second level of transitive dependencies the module versions seems to be wrong.

I attached a small demo project showing the failure:
[demo.zip](https://github.com/jk1/Gradle-License-Report/files/3410376/demo.zip)

When running the task `gradle generateLicenseReport` I get as part of the output:

`{
            "moduleName": "com.fasterxml.jackson.datatype:jackson-datatype-jdk8",
            "moduleUrl": "https://github.com/FasterXML/jackson-modules-java8/jackson-datatype-jdk8",
            "moduleVersion": "2.9.7",
            "moduleLicense": "The Apache Software License, Version 2.0",
            "moduleLicenseUrl": "http://www.apache.org/licenses/LICENSE-2.0.txt"
        },`

The version 2.9.7 for the module jackson-datatype-jdk-8 does not exist.

**Comment by jk1** [comment]
https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.9.7

Am I missing something?

**Comment by sebastiankutschbach** [comment]
Hmm, strange. Seems that this is the correct version. Sorry, my fault!
