### ISSUE TITLE
Wildcard character support  for excludeGroups and excludes 

### ISSUE THREAD

**Issue by jvmlet** [jk1/Gradle-License-Report#152]
It wold be great if one could exclude  `group` and `module:name`  using `*`, i.e.
````groovy
licenseReport {
  excludeGroups = ['do.not.want.*']
    excludes = ['com.foo.*:abc-*']
}
````

**Comment by jk1** [comment]
Implemented as follows: excludes are treated as regular expressions

**Comment by jvmlet** [comment]
Thanks, does `1.10` include this feature ?

**Comment by jk1** [comment]
1.11 has been just released
