### ISSUE TITLE
checkLicense task fails when using imported modules

### ISSUE THREAD

**Issue by jonny-miller** [jk1/Gradle-License-Report#156]
When using imported dependencies (from a DependencyDataImporter), the licenseCheck task fails with the error (in version 1.9):

```
* What went wrong:
Execution failed for task ':checkLicense'.
> Could not find matching constructor for: com.github.jk1.license.check.Dependency(org.apache.groovy.json.internal.ValueList)
```

It looks like the issue is that the LicenseCheckerFileReader expects `dependencies` from an imported module to be a single object, but it is actually a list.  All the tests seem to have the incorrect JSON structure for imported modules.  

You can see [here](https://github.com/jk1/Gradle-License-Report/blob/master/src/test/groovy/com/github/jk1/license/check/LicenseCheckerFileReaderSpec.groovy#L225) that it has something like:

```
"dependencies": {
    "moduleName": "module",
    "moduleVersion": "version"
}
```
instead of:
```
"dependencies" [
    {
        "moduleName": "module",
        "moduleVersion": "version"
    }
]
```

**Comment by jk1** [comment]
Merged and released in scope of 1.10
