### ISSUE TITLE
Using the optional Configuration Options 

### ISSUE THREAD

**Issue by CleanHit** [jk1/Gradle-License-Report#164]
I need to examine some projects for license dependencies, unfortunately I've never used Gradle so far. This tool works very good with the standard commands, but I saw that there is a possibility to define own configuration using:
```
import com.github.jk1.license.render.*
import com.github.jk1.license.importer.*

licenseReport {
....
excludeGroups = ['do.not.want'] 
excludes = ['moduleGroup:moduleName']
renderers = [new XmlReportRenderer('third-party-libs.xml', 'Back-End Libraries')]
importers = [new XmlReportImporter('Frontend dependencies', file(frontend_libs.xml))]
allowedLicensesFile = new File("$projectDir/config/allowed-licenses.json")
.....
}
```
I need to set the configuration attributes above manually, for example in order to exclude some dependencies or generate an XML output instead of the 'index.html'. Do I need to put the block above as it is in the app build.graldle, main build.gradle or in a separate .gradle file for it to work? I know I'll have to change the values of the variables to suit my purpose.

**Comment by jk1** [comment]
The answer really depends on the structure of the build.
Placing the configuration into the same file you apply the plugin in is probably your best bet.

**Comment by CleanHit** [comment]
> Placing the configuration into the same file you apply the plugin in is probably your best bet.

I tried putting in into the same gradle.build file with the where I apply the plugin and I got a gradle error for those lines when scanning license dependencies.

**Comment by jk1** [comment]
Can't help you with that unless you share the error message at least

**Comment by CleanHit** [comment]
> Can't help you with that unless you share the error message at least

I will try to do it during this week.

**Comment by CleanHit** [comment]
I got it wotking
