### ISSUE TITLE
The Dependency Licenes Report HTML is Empty

### ISSUE THREAD

**Issue by CleanHit** [jk1/Gradle-License-Report#167]
My gradle.build file in the app folder imports the app dependencies from a separate file. 

1. When I use this plugin on the setting above I get a blank license result page. 
2. When I copy the app dependencies from the separate file into the gradle.build file where I apply this tool I get same blank license page result.

This is weird, because this tool works on some other project where the app dependencies are directly in the same gradle.build file as the apply for this tool **(2nd setting above)**.

I'm wondering, why can't I get the License dependencies when the app dependencies are in a separate file?

**Comment by CleanHit** [comment]
@jk1 do you have any insights on why this might me happening? Unfortunately, there is no error code just a blank page result.

I already tried without success to minimize the dependences list and get a license result for only one package.

**Comment by CleanHit** [comment]
I get a lot of licenses if I use:
```
licenseReport {
    projects = [project] + project.subprojects
    configurations = ALL
}
```
I don't want all the licenses, only the dependencies of `implementation`. What are the allowed `configurations =` values for the `Gradle-License-Report`?

**Comment by jk1** [comment]
> What are the allowed configurations = values for the Gradle-License-Report

Configuration is one of the basic Gradle concepts: https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html. Any resolvable configuration the project has can be used by the Gradle-License-Report plugin.

**Comment by CleanHit** [comment]
It looks like both of the problematic projects use `flavors` that must be included in the setting of the `configurations` flag. After setting the right `configurations` flag in one project I got the results. I'll try to do the same in the other project tomorrow, but I think it should also work.

**Comment by choudharypranay** [comment]
I solved it by adding the following configuration:
```
    licenseReport {
        configurations = ['debugCompileClasspath','releaseCompileClasspath',
                          'debugRuntimeClasspath','releaseRuntimeClasspath',
                          'debugAndroidTestRuntimeClasspath','releaseAndroidTestRuntimeClasspath',
                          'debugUnitTestRuntimeClasspath', 'releaseUnitTestRuntimeClasspath']
    }
```
https://github.com/jk1/Gradle-License-Report#my-report-is-empty-or-contains-wrong-dependencies-is-it-a-plugin-bug was of some help. if `./gradlew dependencies` gives `No configurations` you may get an empty report. run `./gradlew :app:dependencies` to see your project's dependencies. Select the resolvable dependencies required in your report. Note that `configurations = ['ALL']` did not work for me.
