### ISSUE TITLE
Can't find any releases after 1.3 on gradle.org

### ISSUE THREAD

**Issue by markusadelsberger** [jk1/Gradle-License-Report#168]
Hi,

I can't find any releases after 1.3 on plugins.gradle.org, my build fails if I specify the version number directly. According to the maven-metadata.xml the directory
[maven-metadata.xml.txt](https://github.com/jk1/Gradle-License-Report/files/3944063/maven-metadata.xml.txt)
 was last updated in October 2018.

On the overview page the version 1.12 is shown, but using this version fails for me. This is where gradle would have checked: https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/gradle-license-report/

Was something deleted or am I missing something?

I use the plugin twice in my program, I extend a renderer and I then use it later on.

In my buildSrc\build.gradle (currently with 1.3, with 1.12 the plugin isn't found)
`dependencies {compile 'gradle.plugin.com.github.jk1:gradle-license-report:1.3'}
`

And in my main build.gradle
`plugins {id "com.github.jk1.dependency-license-report"}`

I've attached the maven-metadata.xml in case I'm just seeing some old data.

Thanks,

Markus

**Comment by jk1** [comment]
According to https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report the latest plugin version (1.12) is still there.

> my build fails if I specify the version number directly

Would you mind sharing the error message? Also, what Gradle version you're using?

**Comment by markusadelsberger** [comment]
Hi,
thanks for the super fast response 👍 

I'm currently on Gradle 5.6.2.

> gradlew.bat --version
> 
> ------------------------------------------------------------
> Gradle 5.6.2
> ------------------------------------------------------------
> 
> Build time:   2019-09-05 16:13:54 UTC
> Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781
> 
> Kotlin:       1.3.41
> Groovy:       2.5.4
> Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
> JVM:          1.8.0_222 (Azul Systems, Inc. 25.222-b10)
> OS:           Windows 10 10.0 amd64

The error is:

> gradlew.bat generateLicenseReport
> Starting a Gradle Daemon, 1 busy and 3 stopped Daemons could not be reused, use --status for details
> > Task :buildSrc:compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':buildSrc:compileJava'.
> > Could not resolve all files for configuration ':buildSrc:compileClasspath'.
>    > Could not find gradle.plugin.com.github.jk1:gradle-license-report:1.12.
>      Searched in the following locations:
>        - https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.pom
>        - https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.jar
>        - file:/C:/Users/mad/.m2/repository/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.pom
>        - file:/C:/Users/mad/.m2/repository/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.jar
>        - https://repo.maven.apache.org/maven2/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.pom
>        - https://repo.maven.apache.org/maven2/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.jar
>        - https://jcenter.bintray.com/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.pom
>        - https://jcenter.bintray.com/gradle/plugin/com/github/jk1/gradle-license-report/1.12/gradle-license-report-1.12.jar
>      Required by:
>          project :buildSrc
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

**Comment by jk1** [comment]
Thanks. It may have something to do with the way you declare the plugin dependency.
The following code works for me flawlessly:
```
plugins {
    id 'com.github.jk1.dependency-license-report' version '1.12'
}
```

**Comment by markusadelsberger** [comment]
I wrote a renderer for myself and copied the gradle statements from here, I think the doc might be old at this point ->
https://github.com/jk1/Gradle-License-Report#writing-custom-renderers-importers-and-filters

I just tried, when I change it to this it works:
`compile 'com.github.jk1:gradle-license-report:1.12'`

Previously I had the same as your example:
`compile 'gradle.plugin.com.github.jk1:gradle-license-report:1.12'`

**Comment by jk1** [comment]
It sure is, thanks for reporting it
