### ISSUE TITLE
InventoryHtmlReportRenderer generates multiple matches of the same module / artifact when using LicenseBundleNormalizer

### ISSUE THREAD

**Issue by flitzie** [jk1/Gradle-License-Report#171]
Hello,

I am using Gradle 5.2.1 and GLR v.0.12. I have noticed that InventoryHtmlReportRenderer generates multiple matches of the same module / artifact just by using `new LicenseBundleNormalizer(...)`, even with the default resource:

`licenseReport {`
`   excludeGroups = [ 'my.company.*' ]`
`   excludeOwnGroup = true`
`   renderers = [`
`      new CsvReportRenderer(),`
`      new InventoryHtmlReportRenderer(),`
`      new XmlReportRenderer()`
`   ]`
`   `
`   filters = [`
`      new ReduceDuplicateLicensesFilter(),`
`      //new LicenseBundleNormalizer(bundlePath: "${rootProject.projectDir}/gradle/resources/license-report/my-license-normalizer-bundle.json")`
`      new LicenseBundleNormalizer(bundlePath: "${rootProject.projectDir}/gradle/resources/license-report/default-license-normalizer-bundle_v0.12.json")`
`   ]`
`}`

As soon as I uncomment the last line and GLR uses its own internal default json resource file then there are no duplication of the same modules.

I'd like to use my own license-normalizer-bundle.json file in combination with ReduceDuplicateLicensesFilter().
It also looks like that CsvReportRenderer() and XmlReportRenderer() are working well together with ReduceDuplicateLicensesFilter().

Can you check and verify this issue please?

Thank you in advance.

**Comment by dennisjansen** [comment]
I have the same problem. If i use the LicenseBundleNormalizer in combination with the InventoryHtmlReportRenderer i get strange results.

**Comment by guenhter** [comment]
Could you provide the gradle script (especially the section of your dependencies)?

**Comment by dennisjansen** [comment]
Here are the dependencies from our gradle.build and the bundle normalizer json. IIf you need more information, please let me know.
[dependencies.txt](https://github.com/jk1/Gradle-License-Report/files/4190567/dependencies.txt)
[license-normalizer-bundle.txt](https://github.com/jk1/Gradle-License-Report/files/4190568/license-normalizer-bundle.txt)

**Comment by marioschlipf** [comment]
We are experiencing the same issue. Does the information provided by @dennisjansen help? Otherwise I may be able to provide information from our setup as well.

**Comment by marioschlipf** [comment]
Looks like this problem is related to the option `createDefaultTransformationRules` in the LicenseBundleNormalizer. This option is enabled by default.

**Comment by karbi** [comment]
I believe it happens when dependency matches more then one rule, even for the same bundle. In attached example dependency will appear twice if matches both `licenseNamePattern` and `licenseUrlPattern`. My workaround is using only `licenseNamePattern` rules with explicit names, i.e.:

```{ "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache 2 License$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache License version 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache License, Version 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache License, version 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache License 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^Apache-2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^The Apache License, Version 2.0$" },
    { "bundleName" : "Apache-2.0", "licenseNamePattern" : "^The Apache Software License, Version 2.0$" }
```
It probably could be replaced with single pattern, but it's quick and dirty temporary solution.

**Comment by karbi** [comment]
Turned out that `InventoryHtmlReportRenderer` could add module to each bundle twice, first for pom license and second for manifest license.

**Comment by amotl** [comment]
Hi @jk1,

we are currently observing the same problem, see https://github.com/crate/crate/pull/11220#discussion_r678356606. Is there any chance you could issue a 1.18 release?

With kind regards,
Andreas.

**Comment by jk1** [comment]
@amotl sure, no problem.
I'm about to release 1.18 this week, as soon as I manage to implement full Gradle 7.X support.

I appreciate your patience and understanding.

**Comment by amotl** [comment]
Dear @jk1,

thanks a stack for your efforts, in advance, on also implementing support for Gradle 7.x. Please take your time.

With kind regards,
Andreas.

**Comment by jk1** [comment]
@amotl thank you for your patience. Plugin version 2.X is out. It requires Gradle 7+ though, so please let me know if you need the patch backported.

**Comment by amotl** [comment]
Dear @jk1,

thanks a stack for your quick response and for releasing version 2.0. As our build system has been upgraded to Gradle 7.0 on behalf of https://github.com/crate/crate/pull/11287 the other day, I believe there is no specific need for a backport for us.

With kind regards,
Andreas.
