### ISSUE TITLE
Use a URL for allowed licenses configuration

### ISSUE THREAD

**Issue by patst** [jk1/Gradle-License-Report#173]
Hi there,

we would like to use a central allowed license file stored as static asset somewhere on a server. Then we would like to reference it in the LicenseChecker task.
At the moment the `allowedLicenseFile` is a File object which makes it impossible.

An option would be to add another configuration property (`allowedLicenseFileURL`?) and check that not a local file and a url are configured.
The `LicenseCheckerFileReader` class can then use the URL to load the license configuration.

What do you think?

**Comment by guenhter** [comment]
Cool idea.

**Comment by jk1** [comment]
Released in 1.13
