### ISSUE TITLE
Release 1.12 does not have .module metadata file but states inside the pom that it would have one

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [jk1/Gradle-License-Report#175]
The version 1.12 states in the .pom that it also has a .module metadata file. Therefore gradle (starting with version 6.0) tries to fetch that .module file from the repo and gets an error causing the gradle build to fail.

This could be a deployment problem, perhaps the .module file was dropped during the deployment to the repo.

**Comment by jk1** [comment]
I believe that recent plugin releases are fine.
If not, please let me know.
