### ISSUE TITLE
Add support for the new `compileOnlyApi` dependency scope

### ISSUE THREAD

**Issue by yuri-sergiichuk** [jk1/Gradle-License-Report#196]
Gradle 6.7 has [introduced](https://docs.gradle.org/6.7.1/release-notes.html#new-dependency-management-features) the new `compileOnlyApi` dependency scope that is not currently supported by the plugin. It'd be great to support it as well.

**Comment by jk1** [comment]
Thank you for reaching out.

As far as I can see, `compileOnlyApi` is just another configuration. `scope` is a Maven term and doesn't make much sense when we're taking Gradle.

The plugin requires no specific support for `compileOnlyApi`, as there's already an option to specify configurations to collect dependencies from:

```
// Adjust the configurations to fetch dependencies, e.g. for Android projects
configurations = ['compile']
// Use 'ALL' to dynamically resolve all configurations:
// configurations = ALL
```

as described in the readme.

**Comment by yuri-sergiichuk** [comment]
@jk1 thx for the reply. Yep, looks like it's not a plugin issue, but probably an issue of our configuration.
