### ISSUE TITLE
How to run in doLast {} ?

### ISSUE THREAD

**Issue by tofi86** [jk1/Gradle-License-Report#20]
Hi,
thanks for the good plugin!

I have one question: how can I run this in `doLast {}` phase?

I have 3 of the following tasks:

```gradle
task buildPackage1 {
  def buildDirLibs = "package1/lib/
  doLast {
    delete fileTree(buildDirLibs) { include '*.jar' }
    copy {
      from configurations.path1+ configurations.path2+ configurations.path3+ configurations.path4
      into buildDirLibs
    }
    licenseReport {
      configurations = ['path1', 'path2', 'path3', 'path4']
      renderer = new TextReportRenderer("$buildDirLibs/LICENSES.txt")
    }
  }
}
```

but when I run `gradle buildPackage1` the generateLicenseReport task isn't executed.

The problem ist, that every of my tasks `buildPackage1`, `buildPackage2` and `buildPackage3` needs to have its own `configurations` object and sets a specific `buildDirLibs` variable.
So I need different configurations for the `licenseReport`.

How can I do this?

Thanks,
Tobias

**Comment by jk1** [comment]
Hi Tobias,

> but when I run gradle buildPackage1 the generateLicenseReport task isn't executed.

That's how gradle works. If you want a task to be executed you should either call it explicitly or have a task dependency on it. Your current code seems to do neither.

It's worth mentioning, that licenseReport { ... } is a configuration closure only. It does not execute anything per se, but rather defines how generateLicenseReport  should behave.

**Comment by tofi86** [comment]
Thanks for your quick reply.

Mentioning the configuration closure only gave me some thoughts and this is what I came up with and it works:

```gradle
task buildPackage1(dependsOn: 'generateLicenseReport') {
  def buildDirLibs = "package1/lib/
  // configure in configuration phase
  licenseReport {
    configurations = ['path1', 'path2', 'path3', 'path4']
    renderer = new TextReportRenderer("$buildDirLibs/LICENSES.txt")
  }
  doLast {
    delete fileTree(buildDirLibs) { include '*.jar' }
    copy {
      from configurations.path1+ configurations.path2+ configurations.path3+ configurations.path4
      into buildDirLibs
    }
  }
}
```

> If you want a task to be executed you should either call it explicitly ...

I don't know of any method to call the task directly? Is there a solution to call `generateLicenseReport` from `doLast` method?

> ... or have a task dependency on it. Your current code seems to do neither.

Done. Works. 👍

**Comment by jk1** [comment]
I should've been more explicit about this one. What I meant is a CLI call like

`./gradlew buildPackage1 generateLicenseReport`

Task dependency seems to be a better approach anyway.

> Is there a solution to call generateLicenseReport from doLast method?

Well, there is always `task.taskName.execute()`. This approach, however, is [not recommended](https://stackoverflow.com/questions/8979582/how-do-you-execute-a-built-in-gradle-task-in-a-dofirst-dolast-closure) by gradle devs.

**Comment by tofi86** [comment]
Thanks!
