### ISSUE TITLE
Gradle 6.8.1 deprecation warning

### ISSUE THREAD

**Issue by udopt** [jk1/Gradle-License-Report#200]
Running the `generateLicenseReport` task with Gradle 6.8.1 yields the following deprecation warning:

> The compile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

**Comment by jk1** [comment]
Thank you for reporting it.
Please refer to https://github.com/jk1/Gradle-License-Report/issues/161#issuecomment-716223241
