### ISSUE TITLE
License not recognized for JUnit dependency

### ISSUE THREAD

**Issue by ghost** [jk1/Gradle-License-Report#201]
JUnit 5 (org.junit.jupiter:junit-jupiter-api:5.7.0) loads org.junit:junit-bom:5.7.0 as a dependency.

Unfortunately, the plugin fails to find the license:

> Group: org.junit Name: junit-bom Version: 5.7.0
> No license information found 

>     "dependenciesWithoutAllowedLicenses": [
>         {
>             "moduleLicense": null,
>             "moduleVersion": "5.7.0",
>             "moduleName": "org.junit:junit-bom"
>         }
>     ]

**Comment by effad** [comment]
I've also just stumbled across this problem.

**Comment by jk1** [comment]
Fixed by @c00ler in the scope of #208
