### ISSUE TITLE
Consider migration to github actions

### ISSUE THREAD

**Issue by c00ler** [jk1/Gradle-License-Report#209]
As soon as Github now provides a free solution for CI, it makes sense to consider migration from Travis CI to Github Actions. It will improve developer experience, by reducing the number of dependencies. Github Actions have much better integration with the rest of the Github functions. Some documentation that might be helpful [here](https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions).

**Comment by jk1** [comment]
So I gave it a try and seems a way to go indeed.
Thank you for the suggestion.
