### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by herriojr** [jk1/Gradle-License-Report#21]
I am following installation for an Android project

In root build.gradle:

1) In root build.gradle, Add 
`
plugins {
  id "com.github.jk1.dependency-license-report" version "0.3.12" apply false
}
`
2) In root build.gradle, Add
`
subprojects {
    apply plugin: 'com.github.jk1.dependency-license-report'
}
`
3 Execute
`
./gradlew app:generateLicenseReport
`

Results:
This generates an empty license report in `app/builds/reports/dependency-license/index.html` even though I have a ton of third party dependencies.

```
<html>
<head>
<title>Dependency License Report for app</title>
<head>
<body>
<h1>Dependency License Report for app 0.0.1-SNAPSHOT</h1>

<hr />
<p id="timestamp">This report was generated at <em>Mon Aug 21 16:02:28 PDT 2017</em>.</p>
</body>
</html>
```
Expected:
The license report contains all my dependencies

**Comment by herriojr** [comment]
I would also expect transitive dependencies to also be included

**Comment by jk1** [comment]
Have you tried to follow the example in readme?

licenseReport {
    // Adjust the configurations to use, e.g. for Android projects.
    configurations = ['compile']
}
