### ISSUE TITLE
Improving the LicenseBundleNormalizer

### ISSUE THREAD

**Issue by amotl** [jk1/Gradle-License-Report#218]
Dear Evgeny and Günther,

first things first: Thank you again for releasing version 2.0, including the patch #210 by @karbi which fixes #171. After running the current version on behalf of https://github.com/crate/crate/pull/11220, it worked like a charm.

I wanted to take the chance to report about the outcome of the process when invoked on a reasonably large Java project with quite a number of dependencies, regarding the default configuration of the `LicenseBundleNormalizer`. Based on this, we might want to improve the [`default-license-normalizer-bundle.json`](https://github.com/jk1/Gradle-License-Report/blob/9fd5d86/src/main/resources/default-license-normalizer-bundle.json).

```
$ cat 3RD-PARTY-NOTICES.md | grep '## '
## Apache License, Version 2.0
## BSD Zero Clause License
## COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0
## COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1
## Creative Commons Legal Code
## Eclipse Distribution License - v 1.0
## Eclipse Public License - v 1.0
## Eclipse Publish License, Version 1.0
## Embedded
## GNU GENERAL PUBLIC LICENSE, Version 2 + Classpath Exception
## GNU General Public Library
## GNU General Public License (GPL), version 2, with the Classpath exception
## GNU Lesser General Public License (LGPL), Version 2.1
## LGPL, version 2.1
## MIT License
## PUBLIC DOMAIN
## The 2-Clause BSD License
## The 3-Clause BSD License
## The BSD License
## Unicode/ICU License
## Universal Permissive License, Version 1.0
## Unknown
```

From looking at this output, I see two spots where the normalization rules might get improved:

1. _Eclipse Publish License_ is probably a typo and can be converged into _Eclipse Public License_.
2. _LGPL, version 2.1_ can probably be converged into _GNU Lesser General Public License (LGPL), Version 2.1_.

With kind regards,
Andreas.

P.S.: Following your encouragement to contribute back useful rules, I was about to submit a corresponding patch, but got blocked by #219.

/cc @guenhter

**Comment by jk1** [comment]
Hi @amotl,

Thank you for sharing the results.
It seems that a number of licenses indeed use `Eclipse Publish License`. Good catch!

**Comment by amotl** [comment]
Sweet. Thank you!
