### ISSUE TITLE
build fails with org.ehcache:ehcache:3.3.1 dependency

### ISSUE THREAD

**Issue by happyviral** [jk1/Gradle-License-Report#22]
Steps to reproduce:

- Add compile dependency org.ehcache:ehcache:3.3.1 in build script (e.g. build.gradle)
- ensure plugin dependency-license-report version is 0.3.12
- run `gradle generateLicenseReport` to generate report
- build error message `Execution failed for task ':generateLicenseReport'. > No such property: path for class: com.github.jk1.license.render.SimpleHtmlReportRenderer`

**Comment by happyviral** [comment]
Created a pull request https://github.com/jk1/Gradle-License-Report/pull/23 to fix the issue

**Comment by jk1** [comment]
Thanks a bunch. Merged and published in scope of 0.3.14.
