### ISSUE TITLE
Download issue caused by bintray's jcenter shutdown

### ISSUE THREAD

**Issue by seut** [jk1/Gradle-License-Report#224]
Today we encountered an issue while trying to download the plugin inside our gradle setup.
The resource at `plugins.gradle.org` redirects to bintray while bintray's SSL cert expired today. Probably caused by their shutdown of jcenter https://blog.gradle.org/jcenter-shutdown.

```
Error happen on GH:
   > Could not resolve com.github.jk1:gradle-license-report:2.0.
     Required by:
         project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:2.0
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
               > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by jk1** [comment]
Thank you for reporting the issue.

The plugin is published with a default Gradle plugin publisher, so I have little control over where it is hosted.
I have observed the similar issue with this plugin only once and it was the DNS cache to blame. There might be something similar going on on your end.

Please let me know if the problem persists and I'll try to reach Gradle devs to comment on that.

**Comment by szczepanskikrs** [comment]
I can confirm the issue

```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.jk1:gradle-license-report:2.0.
     Required by:
         project :
         project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:2.0
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/127.0.0.1] failed: Połączenie odrzucone (Connection refused)
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/127.0.0.1] failed: Połączenie odrzucone (Connection refused)
```

 **How to reproduce:**

Disable access to Jcenter and try to build project using dependency report.

**Comment by abhijeetnarvekar** [comment]
The gradle URL redirects to jcenter

Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.github.jk1:gradle-license-report:2.0.
     Required by:
         project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:2.0
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'. Received status code 502 from server: Bad Gateway

**Comment by dlvenable** [comment]
We are having the same issue on the 1.17 version. (We are stuck on Gradle 6 presently and so have to use the 1.x versions).

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.jk1:gradle-license-report:1.17.
     Required by:
         project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:1.17
      > Could not resolve com.github.jk1:gradle-license-report:1.17.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/1.17/gradle-license-report-1.17.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/1.17/gradle-license-report-1.17.module'. Received status code 502 from server: Bad Gateway
```

**Comment by akleemans** [comment]
We seem to be having the same problem (v1.14):

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project '<projectname>'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.jk1:gradle-license-report:1.14.
     Required by:
         project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:1.14
      > Could not resolve com.github.jk1:gradle-license-report:1.14.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/1.14/gradle-license-report-1.14.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/1.14/gradle-license-report-1.14.module'. Received status code 502 from server: Bad Gateway
```

**Comment by jk1** [comment]
According to https://blog.gradle.org/jcenter-shutdown, section Impact to Gradle plugins

> Behind the scenes, the Gradle Plugin Portal uses JCenter to resolve dependencies of plugins. We will be migrating the Plugin Portal away from JCenter before the final shutdown. Builds will not need to make changes while the Plugin Portal migrates away from JCenter.

> Resolving existing plugins
> Existing plugins will continue to resolve in the same way they do today. No changes should need to be made to your builds.

> Publishing new or updated plugins
> If you are publishing your plugin with the com.gradle.plugin-publish, you are not affected. Just double check that your build does not use JCenter directly.

The plugin does follow the Gradle Dev team recommendations and should be resolvable.
Yet jcenter.bintray.com is down at the moment of writing. 

I'm looking into it right now, stay tuned.

**Comment by mtyeh411** [comment]
we've circumvented this issue for now by resolving plugin from Maven Central
https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories

**Comment by dsvensson** [comment]
Wouldn't releasing it to maven central fix the problem for good?

**Comment by szczepanskikrs** [comment]
If you have this problem try to update your gradle to 7.3 and add plugin management entry to you gradle settings 

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```

When using `gradlePluginPortal()` with Gradle 7.3 builds will no longer need JCenter

**Comment by dlvenable** [comment]
I found a work-around for our project. The Gradle Plugins repository appears to mirror JCenter for the `.module` file. This file is used by default rather than the POM. So I disabled Gradle metadata redirection.

This is working for us on Gradle 6.6.1:

```
buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
            metadataSources {
                mavenPom()
                ignoreGradleMetadataRedirection()
            }
        }
    }
    dependencies {
        classpath 'com.github.jk1:gradle-license-report:1.17'
    }
}
```

And then:

```
apply plugin: 'com.github.jk1.dependency-license-report'
```

**Comment by dsvensson** [comment]
> When using `gradlePluginPortal()` with Gradle 7.3 builds will no longer use JCenter when plugin is migrated

I'm using that setup with the same ideas. It only works if the artifacts are found on mavenCentral which is not the case here. Sure you're not pulling jars from your ~/.gradle directory?

**Comment by dsvensson** [comment]
@dlvenable thanks! alse have to create a settings.gradle.kts in buildSrc if such functionality is used.

**Comment by jk1** [comment]
> Wouldn't releasing it to maven central fix the problem for good?

It could be. Yet releasing anything to maven central may take days to get everything approved.
The latest status update on the global issue is available at https://status.gradle.com/incidents/nv93msj8q658.

**Comment by jk1** [comment]
It seems that the issue has been fully resolved from the Gradle side
