### ISSUE TITLE
Plugin [id: 'com.github.jk1.dependency-license-report', version: '2.1'] was not found

### ISSUE THREAD

**Issue by amotl** [jk1/Gradle-License-Report#228]
Dear Evgeny,

thanks a stack for working on #218 and #224 and kudos for releasing version 2.1. On this matter, I just wanted to report back to you, that, when bumping to version 2.1, it croaked like outlined below.

Maybe the publishing process is still ongoing or has not finished yet? There might also be chances that I am missing something here? FWIW, we are on `gradleVersion = '7.3.3'`, see also [`CrateDB's build.gradle`](https://github.com/crate/crate/blob/98685b7/build.gradle).

With kind regards,
Andreas.

```
sink:crate amo$ ./gradlew generateLicenseNotes

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/amo/dev/crate/sources/crate/build.gradle' line: 35

* What went wrong:
Plugin [id: 'com.github.jk1.dependency-license-report', version: '2.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:2.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by jk1** [comment]
Hi Andreas,

Thank you for the heads up. I believe I see where the issue is. The script I use to publish things got rate limited by Gradle Plugin Portal, so the plugin update didn't actually make it.

I've republished it from a different machine and it seems to be OK now.

**Comment by amotl** [comment]
Hi Evgeny,

I can confirm this works now, see https://github.com/crate/crate/pull/12061. Thanks again!

With kind regards,
Andreas.
