### ISSUE TITLE
Report generation needs to account for filter changes

### ISSUE THREAD

**Issue by bdellegrazie** [jk1/Gradle-License-Report#231]
Hi,

We're running version 2.1 with a Gradle remote build cache in CI on Gradle 7.3.3.
We're using a custom transform filter `LicenseBundleNormalizer` that includes slight modifications for variances we've seen.

However, if we execute a build in CI _prior_ to updating the license bundle normalizer json file to map a new variance, the build will continuously fail in CI - even if we update the branch and confirm the fix works locally.

In essence, the report content that is cached needs to depend upon any filters in use, particularly the license bundle normalizer file, otherwise Gradle's caching tech will simply mark the report as up-to-date.

This issue is exacerbated by remote caching because the task doesn't indicate the filter file(s) as contributors to the report.
It's less obvious normally because a `gradle clean` and a wipe of the local disk cache (if configured) will remove the problem.

I believe this may be the root cause of several other active issues too such as #223, #219, #217, #182
It's quite possible PR https://github.com/jk1/Gradle-License-Report/pull/166 will go some way to resolving this.

**Comment by jk1** [comment]
@bdellegrazie I believe you're right. Will integrate #166 into 2.2 to address it.

**Comment by bdellegrazie** [comment]
Thanks!
