### ISSUE TITLE
Release 2.1 uses Java class file version 55

### ISSUE THREAD

**Issue by jenschude** [jk1/Gradle-License-Report#241]
Releases before 2.1 were compiled with a target runtime for Java 8. The latest releases 2.1 was compiled with Java 11. Could you please build the plugin against Java8 again?

It could also help to define the target runtime in the build.gradle

**Comment by jk1** [comment]
Hi @jenschude. Unfortunately, 2.X builds require Java 11. Reverting this change will result in a number of variant-aware plugin binary resolution issues. Please use 1.X builds instead. They were deliberately left on Java 8.

**Comment by jk1** [comment]
> Reverting this change will result in a number of variant-aware plugin binary resolution issues

I did more testing on my side and everything seems to be fine. 
Let's have it java 8 compatible then.

**Comment by jenschude** [comment]
Thanks for the effort.

Wasn't able to take a look at it again.
