### ISSUE TITLE
Missing detailed documentation for using buildscript style

### ISSUE THREAD

**Issue by chubbard** [jk1/Gradle-License-Report#25]
Since this is a fork the forked version includes documentation for plugin { id } style syntax and includes how to include it in a buildscript.  The buildscript syntax is important because in multi-module projects you can provide this configuration in a single location and apply it to all sub-projects.  The problem with the lack of documentation is figuring out the dependency group/name/version strings.  I'll cut to the chase:

    buildscript {
       repositories {
            jcenter()
       }

       dependencies {
           classpath 'gradle.plugin.com.github.jk1:gradle-license-report:0.3.12'
       }
    }
    apply plugin: 'com.github.jk1.dependency-license-report'

This would be really nice to add to the README.md so it's easier to leverage it.

**Comment by jk1** [comment]
Fair enough. Thanks for the pull request.
