### ISSUE TITLE
Versions/releases after 1.16 are not tagged

### ISSUE THREAD

**Issue by psibre** [jk1/Gradle-License-Report#250]
Somewhat related to #168 and #64, I don't see any tags or releases in this project after 1.16 (from 2020). But clearly development is alive and well, and https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report does indeed list the latest release as 2.1.

Would it be possible to push the missing tags, so that users of this plugin can at least compare releases? (A changelog would also be great!)

**Comment by jk1** [comment]
Relent releases have versions and tags defined.
I did my best to restore historical tags from 1.17 till 2.1, but these may be a bit off.
