### ISSUE TITLE
Request for Version 2.2 for the gradle plugin

### ISSUE THREAD

**Issue by VachaShah** [jk1/Gradle-License-Report#251]
Thank you for this plugin!

We want to upgrade to the 2.x line of this plugin but facing issues for the LicenseDataCollector as mentioned in #239. I see that the issue is fixed in #240 but needs to be released as a newer version in the 2.x line.

It would be very helpful to have a 2.2 version with this fix. TIA!

**Comment by breedx-splk** [comment]
+1. Can we get a release?
For [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) we could use the fix from #235 as well (the [report headings](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/licenses/licenses.md) are broken). Thanks!

**Comment by bric3** [comment]
It'd be neat to update the READ / and github release as it's a tad confusing regarding the actual latest version.

**Comment by pjfanning** [comment]
Would it be possible to push future releases to MavenCentral? https://repo1.maven.org/maven2/

JCenter is being shut down. I just got this in a build today:

```
  > Could not resolve com.github.jk1:gradle-license-report:2.0.
    Required by:
        project : > com.github.jk1.dependency-license-report:com.github.jk1.dependency-license-report.gradle.plugin:2.0
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
        > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
              > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
      > Could not resolve com.github.jk1:gradle-license-report:2.0.
        > Could not get resource 'https://plugins.gradle.org/m2/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
            > Could not GET 'https://jcenter.bintray.com/com/github/jk1/gradle-license-report/2.0/gradle-license-report-2.0.module'.
              > sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
```

**Comment by chadlwilson** [comment]
FWIW 2.2 was released yesterday: https://github.com/jk1/Gradle-License-Report/releases/tag/v2.2

Bit hard to see what the diff is as no tags for 2.0 or 2.1 but I guess the fixes you are looking for are there.
