### ISSUE TITLE
Release 2.0 missing on releases page

### ISSUE THREAD

**Issue by albertotn** [jk1/Gradle-License-Report#266]
Could you please add release 2.0 on releases page ?
Using systems like https://jitpack.io/#jk1/Gradle-License-Report doesn't shows up

**Comment by jk1** [comment]
If you don't mind me asking, what's the purpose of using jitpack.io for gradle plugins? Isn't the official plugin repo good enough?

**Comment by albertotn** [comment]
No problem, sometimes I'm trying to find quick way to do it and jitpack ( due to firewalls and so on ) works fine

**Comment by jk1** [comment]
Published release 2.2
