### ISSUE TITLE
Add a renderer that organizes by unique licenses to make it easier to analyze

### ISSUE THREAD

**Issue by chubbard** [jk1/Gradle-License-Report#27]
In larger projects many of the libraries share a common license, but finding that information out is difficult.  Create a renderer that organizes dependencies by licenses and give you a table of contents or a way to navigate between licenses and dependencies.

**Comment by chubbard** [comment]
Pull Request #28

**Comment by jacek99** [comment]
any news if a new version gets released with this? uit would be super useful[

**Comment by jk1** [comment]
It would, for sure. I'm going to check and merge it on a weekend.

**Comment by chubbard** [comment]
Thanks for accepting this change!  Any ideas on when you might make another release?

**Comment by jk1** [comment]
Just released it as 0.3.15. Please note, that InventoryHtmlReportRenderer now takes one additional parameter to customize report file name.

**Comment by jacek99** [comment]
Can you tell us how to use this? I just upgraded to 0.3.15 and the report looks the same?
Also, the docs on the main page still mention 0.3.14 and there seems to be no docs on how to override the report name...thanks!

**Comment by chubbard** [comment]
Yes I'll update the Readme file with instructions on how it works.  Sorry for not doing that.

**Comment by jacek99** [comment]
I guessed by looking at the code it would be something like this:
```
    licenseReport {
        renderer = new com.github.jk1.license.render.InventoryHtmlReportRenderer('third-party-license-report.html')
    }
```
