### ISSUE TITLE
Please make comptible with java 8 again

### ISSUE THREAD

**Issue by bratkartoffel** [jk1/Gradle-License-Report#270]
Hi,

with #226 the compile target was changed from 8 to 11, although the comments read like this wasn't really needed. @etiennecadicidean, can you confirm this?

As the company I work for uses this plugin, but is still stuck with java 8 (legacy software, yey) I kindly ask you to change the level back to 8 again. As far as I can see this should not be an issue.

Thanks,
Simon

**Comment by bratkartoffel** [comment]
Is the 1.x branch still maintained? Last release was about 2.5 years ago, so I guess no. Have to try it with our projects though.

**Comment by etiennecadicidean** [comment]
@bratkartoffel can you confirm from your side the plugin is working with the 2.X branch without the Java_11 setting ? 
Are you working on an Android project ? if yes, the android build gradle plugin based on gradle 7+ requires java 11 anyway.

**Comment by bratkartoffel** [comment]
Our projects are plain old java, no android involved.

The 2.0 release is working just fine, it stopped working with the 2.1 release as the java level changed there. I'm new to gradle plugin development, have to try to build and test it locally on tuesday. I don't expect any problems though.

**Comment by jk1** [comment]
I revisited the issue and did some more testing on my side.
Well, you were right. No variant-aware resolution issues that I've seen before. So it should be fine to revert the java version.
