### ISSUE TITLE
Root dependency unknowen for Kotlin multiplatform dependencies

### ISSUE THREAD

**Issue by JochenGuckSnk** [jk1/Gradle-License-Report#272]
Hi 

im unsing this plugin in a kotlin multiplatform project. The licens resolution works for the target specific dependencies like:
co.touchlab:stately-common-jvm:1.2.5 
how ever if it comes to the root dependency 
co.touchlab:stately-common:1.2.5 
the license is unknowen.

I provided the licens information of the -jvm sufix for the sufix less name via unknown-license-details.txt and resolved all unknowen dependecies.

Is there an oportunety to us the licence of the target specific package for the root package if there is no licences specified?

**Comment by trask** [comment]
we're having the same problem with `com.squareup.okio:okio` (which is a multiplatform dependency that then pulls in `com.squareup.okio:okio-jvm`):

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/licenses/licenses.md#unknown

**Comment by zhurs** [comment]
@jk1 Here is a example of problem:
https://github.com/jk1/Gradle-License-Report/commit/eb0b3f27f8a67bc82da6ccf8fd3579430300a7f3

**Comment by jk1** [comment]
A filter introduced in #280 is expected to solve the problem
