### ISSUE TITLE
No license detected for `org.jetbrains.kotlinx:kotlinx-coroutines-core`

### ISSUE THREAD

**Issue by adiykehler** [jk1/Gradle-License-Report#275]
The dependency `org.jetbrains.kotlinx:kotlinx-coroutines-core` contains a license in the [POM](https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.7.3/kotlinx-coroutines-core-1.7.3.pom) published online. For some reason, the artifact is never processed during license generation. It is included in the logs as a dependency:

```
Processing dependencies for configuration [configuration ':bundles:full']: [redacted];jvmRuntimeElements-published,org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.7.3;platform-runtime,org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3;jvmRuntimeElements-published,org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.3;jvmRuntimeElements-published,org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.7.3;[redacted]
```

In the logs no line `Processing artifact:...` appears for that dependency. Probably because there is only a `-metadata.jar` and `sources.jar` for that dependency. 

In contrast the transitive dependency `org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm` is correctly processed.
```
        {
            "moduleName": "org.jetbrains.kotlinx:kotlinx-coroutines-core",
            "moduleVersion": "1.7.3"
        },
```

I would expect that either the dependency is ignored and not included at all, or that the license from the POM is used. 

I can exclude this dependency as a workaround, but since this is a very common artifact and rather common use-case, a lot of people would profit from an an improvement to this plugin. 

Let me know, if I can do anything to help.

## Additional Information
I am using 
- com.github.jk1.dependency-license-report version 2.5
- gradle version 8.3

**Comment by adiykehler** [comment]
This seems to be a recurring problem for multiplatform modules in Kotlin. So in fact this is a duplicate of #272

Other dependencies with similar problems:
- `com.michael-bull.kotlin-result:kotlin-result` with `com.michael-bull.kotlin-result:kotlin-result-jvm` having a license
- `com.michael-bull.kotlin-result:kotlin-result-coroutines` with `com.michael-bull.kotlin-result:kotlin-result-coroutines-jvm` having a license
- `io.ktor:ktor-client-cio` with `io.ktor:ktor-client-cio-jvm`
- `io.ktor:ktor-client-core` with `io.ktor:ktor-client-core-jvm`
- `io.ktor:ktor-client-java` with `io.ktor:ktor-client-java-jvm`
- `io.ktor:ktor-client-json` with `io.ktor:ktor-client-json-jvm`
- `io.ktor:ktor-events` with `io.ktor:ktor-events-jvm`
etc.

**Comment by jk1** [comment]
@adiykehler why closing it? It seems to be a valid concern to address

**Comment by adiykehler** [comment]
@jk1 Because it's already reported with #272, and thus a duplicate. Feel free to reopen :)

**Comment by jk1** [comment]
Fair enough, thanks
