### ISSUE TITLE
Missing from repository?

### ISSUE THREAD

**Issue by chubbard** [jk1/Gradle-License-Report#36]
So the plugin has disappeared on jcenter.

https://jcenter.bintray.com/com/github/jk1/gradle-license-report/

What's up?  Where did it go?

**Comment by jk1** [comment]
Well, I haven't removed anything from there. Plugin repository itself still has the plugin available though: https://plugins.gradle.org/plugin/com.github.jk1.dependency-license-report

**Comment by chubbard** [comment]
But did you visit the jcenter link I included?  I don't see anything.

**Comment by jk1** [comment]
I did, can't see it either. 
Why is it a problem? Gradle builds seem to resolve the plugin correctly as before.

**Comment by chubbard** [comment]
Well you probably have it cached.  If I build the plugin and install it locally with maven or if I had already downloaded it before it disappeared then I wouldn't know that it wasn't on the repo.  But if you removed your cached copy you should start seeing the problem as well.

**Comment by jk1** [comment]
It doesn't seem to be the case as I can see gradle downloading the plugin:

```
jk1@jk1-Aspire-3830T:~/Projects/test$ ./gradlew
Parallel execution with configuration on demand is an incubating feature.
:buildSrc:compileJava NO-SOURCE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources NO-SOURCE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava NO-SOURCE
:buildSrc:compileTestGroovy NO-SOURCE
:buildSrc:processTestResources NO-SOURCE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test NO-SOURCE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/gradle-license-report/0.3.16/gradle-license-report-0.3.16.pom
Download https://plugins.gradle.org/m2/gradle/plugin/com/github/jk1/gradle-license-report/0.3.16/gradle-license-report-0.3.16.jar

```

Please provide me with a minimum build config example that fails for you.

**Comment by chubbard** [comment]
Ok you're right.  It was the gradle.plugin prefix was missing from my classpath.  When I was working locally gradle.plugin prevented me from using the compiled version I had locally to test.  And while the full URL will download the jar/pom any other URL doesn't route.  You can close this out.
