### ISSUE TITLE
Wrong POM for Realm Dependency

### ISSUE THREAD

**Issue by tomquist** [jk1/Gradle-License-Report#4]
I've the following dependency in my project: 'io.realm:realm-android:0.82.2'
However, the following URL is resolved for this dependency: http://github.com/square/javawriter/

Looking into Realms POM-File, there is no mention to javawriter (https://bintray.com/artifact/download/realm/maven/io/realm/realm-android/0.82.2/realm-android-0.82.2.pom)

Do you have any idea what's going on here?

**Comment by jk1** [comment]
I guess I do. realm-android has javawriter with it's own license packaged inside, see /meta-inf/maven. It's still a plugin issue though, as  correct url is present in library's own pom.

**Comment by guenhter** [comment]
Same happens for `org.ehcache:ehcache`. Here the url is resolved to `https://github.com/ehcache/sizeof`

**Comment by jk1** [comment]
Integrated and released in 0.8
