### ISSUE TITLE
Task output is not set

### ISSUE THREAD

**Issue by ledan87** [jk1/Gradle-License-Report#8]
Instead of setting the value outputDir I would recommend to use the 'output.dir'-property. This would enable the output of generateLicenseReport to be used for other tasks, e.g.:
```
distributions{
  main {
    contents {
      from(generateLicenseReport) {
        into 'license'
      }
    }
  }
}
```
Currently I need to do it this way in my script:
```
afterEvaluate {
  generateLicenseReport {
    outputs.dir licenseReport.outputDir
  }
}
```
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_inputs_outputs

**Comment by jk1** [comment]
Good catch, thanks
