### ISSUE TITLE
Task is `UP-TO-DATE` when a new dependency is added

### ISSUE THREAD

**Issue by ketan** [jk1/Gradle-License-Report#83]
The `LicenseReport` task uses the [`getSnapshot()`](https://github.com/jk1/Gradle-License-Report/blob/master/src/main/groovy/com/github/jk1/license/ReportTask.groovy#L32) method to decide if the inputs have changed.

However simply adding/removing/updating a dependency on a project does not cause the `getSnapshot` to return a different value from before, thereby causing an incorrect license report to be generated.

**Comment by guenhter** [comment]
Yeah, I ran into the same problem. This really should get fixed.
I guess you can solve it by adding the `clean` task to your gradle tasks (but this have usually some severe performance issues and breaks the incremental build)
