### ISSUE TITLE
More examples and clarifications on Importers would be useful

### ISSUE THREAD

**Issue by amimas** [jk1/Gradle-License-Report#87]
Hello,

As I'm going through the readme of this plugin, I'm finding the information on **Importers** is not quite clear and it'd be useful to have some more examples/clarifications. Maybe it's not clear to me only. I'd appreciate if you could help me understand it better.

```markdown
Importer adds license information from an external source to your report. Importer may come in handy if

- some modules within your application use their own means of library dependency resolution, e.g. npm registry

- your application integrates third party components or services with their own library dependencies

- joint report for a multimodule project is required
```

It'd be nice if you have an example of the dependency resolution using npm registry. Does this plugin automatically detect `package.json` file or do I need to somehow provide that info?

By default, I believe this plugin automatically generates a report for all projects. At least that's what it does for me. I have a multi module project. I applied this plugin to the root project and it is giving me a report containing dependencies of all the sub projects. I didn't use any "importer". So, not really sure what the 3rd point means by "joint report for a multimodule poject". Do you have an example?

**Comment by jk1** [comment]
Importer just allows to plug in any additional dependency information one may have, regardless of its source.

> It'd be nice if you have an example of the dependency resolution using npm registry.

It may work as follows: 
- One builds frontend part with npm and backend part with gradle
- Some custom code within an npm build stack generates license report based on npm data and dumps it into a file
- There's an importer implemented in gradle build to digest the file
- Gradle plugin generates joint report with all dependency data included

>  So, not really sure what the 3rd point means by "joint report for a multimodule poject"

It makes no sense for you as you've applied the plugin to the root project. If the plugin is applied only to ceratin submodules, then they can share dependency data thanks to importers.

**Comment by jk1** [comment]
> Do I need to implement that "custom code" for the npm build to generate a license report?

Yes, indeed. Although tools like https://www.npmjs.com/package/license-checker may do the most part of the job.

**Comment by amimas** [comment]
Thanks. I'll look into that.
