### ISSUE TITLE
Updated bundle json file for better grouping dependencies

### ISSUE THREAD

**Issue by amimas** [jk1/Gradle-License-Report#89]
The license data grouping is a very useful feature. I used the default one that comes with the plugin, but still noticed a few dependencies were not grouped properly.

For example, I had 1 dependency under each of the following groups:
* Apache License 2.0
* Apache License Version 2.0

Also had 2 dependencies under **CDDL 1.0** and 1 dependency under **Common Development and Distribution License (CDDL) v1.0**

I slightly updated so that everything related Apache 2.0 gets grouped together and CDDL 1.0 related items are grouped together. Here's my bundle json file.

```json
{
    "bundles" : [
      { "bundleName" : "apache1", "licenseName" : "Apache Software License, Version 1.1", "licenseUrl" : "http://www.apache.org/licenses/LICENSE-1.1" },
      { "bundleName" : "apache2", "licenseName" : "Apache License, Version 2.0", "licenseUrl" : "http://www.apache.org/licenses/LICENSE-2.0" },
      { "bundleName" : "bsd-2",   "licenseName" : "The 2-Clause BSD License", "licenseUrl" : "https://opensource.org/licenses/BSD-2-Clause" },
      { "bundleName" : "bsd-3",   "licenseName" : "The 3-Clause BSD License", "licenseUrl" : "https://opensource.org/licenses/BSD-3-Clause" },
      { "bundleName" : "cc0",     "licenseName" : "Creative Commons Legal Code", "licenseUrl" : "http://repository.jboss.org/licenses/cc0-1.0.txt" },
      { "bundleName" : "cddl1",   "licenseName" : "CDDL 1.0", "licenseUrl" : "http://opensource.org/licenses/CDDL-1.0" },
      { "bundleName" : "cpl-1.0", "licenseName" : "Common Public License - v 1.0", "licenseUrl" : "https://www.eclipse.org/legal/cpl-v10.html" },
      { "bundleName" : "epl1",    "licenseName" : "Eclipse Public License - v 1.0", "licenseUrl" : "http://www.eclipse.org/legal/epl-v10.html" },
      { "bundleName" : "epl2",    "licenseName" : "Eclipse Public License - v 2.0", "licenseUrl" : "https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt" },
      { "bundleName" : "gpl1",    "licenseName" : "GNU GENERAL PUBLIC LICENSE, Version 1", "licenseUrl" : "https://www.gnu.org/licenses/gpl-1.0" },
      { "bundleName" : "gpl2",    "licenseName" : "GNU GENERAL PUBLIC LICENSE, Version 2", "licenseUrl" : "https://www.gnu.org/licenses/gpl-2.0" },
      { "bundleName" : "gpl3",    "licenseName" : "GNU GENERAL PUBLIC LICENSE, Version 3", "licenseUrl" : "https://www.gnu.org/licenses/gpl-3.0" },
      { "bundleName" : "lgpl2.1", "licenseName" : "GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1", "licenseUrl" : "https://www.gnu.org/licenses/lgpl-2.1" },
      { "bundleName" : "lgpl3",   "licenseName" : "GNU LESSER GENERAL PUBLIC LICENSE, Version 3", "licenseUrl" : "https://www.gnu.org/licenses/lgpl-3.0" },
      { "bundleName" : "mit",     "licenseName" : "MIT License", "licenseUrl" : "https://opensource.org/licenses/MIT" },
      { "bundleName" : "mpl1.1",  "licenseName" : "Mozilla Public License Version 1.1", "licenseUrl" : "https://www.mozilla.org/en-US/MPL/1.1" },
      { "bundleName" : "mpl2",    "licenseName" : "Mozilla Public License, Version 2.0", "licenseUrl" : "https://www.mozilla.org/en-US/MPL/2.0" }
    ],
    "transformationRules" : [
      { "bundleName" : "apache2", "licenseNamePattern" : ".*The Apache Software License, Version 2.0.*" },
      { "bundleName" : "apache2", "licenseNamePattern" : "Apache License .*2.0" },
      { "bundleName" : "apache2", "licenseNamePattern" : "Apache 2.*" },
      { "bundleName" : "apache2", "licenseNamePattern" : "ASL 2.0" },
      { "bundleName" : "apache2", "licenseUrlPattern" : ".*www.apache.org/licenses/LICENSE-2.0.*" },
      { "bundleName" : "lgpl2.1", "licenseUrlPattern" : ".*www.gnu.org/licenses/old-licenses/lgpl-2.1.html" },
      { "bundleName" : "mit",     "licenseUrlPattern" : ".*www.opensource.org/licenses/mit-license.php" },
      { "bundleName" : "apache2", "licenseFileContentPattern" : ".*Apache License, Version 2.0.*" },
      { "bundleName" : "apache1", "licenseFileContentPattern" : ".*Apache Software License, Version 1.1.*" },
      { "bundleName" : "cddl1", "licenseNamePattern" : ".*CDDL.*1.0" }
    ]
}
```

**Comment by guenhter** [comment]
Could you make a PR for this? I guess this is useful.

**Comment by guenhter** [comment]
You changed the license name from `COMMON DEVELOPMENT AND DISTRIBUTION LICENSE Version 1.0 (CDDL-1.0)` to `CDDL 1.0`.
Maybe we should start a bigger discussion here: Is is useful for all licenses to use the short name instead of the full name?

**Comment by guenhter** [comment]
@jk1 what do you think?

**Comment by amimas** [comment]
You bring up a good point. In my case, I had sone dependency showing up under `CDDL 2.0`. There was another dependency that showed up as a combination of CDDL 1.0 and some other license. That's why in my project, I changed the above mentioned license to short form **CDDL 1.0** to keep it consistent.

**Comment by jk1** [comment]
@guenhter I would rather preserve as much information as possible during filtering. Later on, a renderer will decide what to show and what to hide. So my vote goes for a full license name `COMMON DEVELOPMENT AND DISTRIBUTION LICENSE Version 1.0 (CDDL-1.0)`.

**Comment by guenhter** [comment]
Agree.

**Comment by amimas** [comment]
So that means, with default plugin configuration we may see licenses grouped like this:

* COMMON DEVELOPMENT AND DISTRIBUTION LICENSE Version 1.0 (CDDL-1.0)
  * artifact1
  * artifact2
* CDDL 1.1
  * artifact3
  * artifact4

Is that right?

**Comment by guenhter** [comment]
In this particular CDDL case, we only have to include the CDDL 1.1 with its proper full name in the default configuration.
Also, there are still a lot of other licenses which are not included yet. With helpful issues like this, we tackle license by license...

**Comment by amimas** [comment]
The full name for this license is long but I think that's ok. At least keeps the naming consistent.

**Comment by guenhter** [comment]
#99 adds the cddl 1.1 in the default license bundles.

Also I'm thinking of supporting the shortname of a license in addition to the actual full name. Then it would be easy to control with one simple property if the full name or the short name should be used for normalization.

**Comment by jk1** [comment]
#99 has been merged
