### ISSUE TITLE
Hundred of Configurations trigger Artifactory Build Info Issue

### ISSUE THREAD

**Issue by Wadlazky** [jk1/Gradle-License-Report#91]
To resolve the dependencies, the plugin created a Gradle Configuration for every dependency in class CachingArtifactResolver. This results in hundreds of scopes of type POM laying arround after the generateLicenseReport task.
We also use the Artifactory plugins org.jfrog.buildinfo:build-info-*.
Artifactory analyze all scopes of a build and safe the information in an internal Database, comma-separated in one field. So, the great dimension of this scopes-string triggers an exception in Artifactory when the length exceeds the max field length in the database.

Our workaround was to implement a generateLicenseReport.doLast which remove all configurations with name dependencyLicenseReport* from ConfigurationContainer in the hope, there are no side effects, doing this.

**Comment by guenhter** [comment]
Solved with #92

**Comment by jk1** [comment]
Released in the scope of 1.2
