### ISSUE TITLE
Tasks offered by the plugin should have a group and description

### ISSUE THREAD

**Issue by amimas** [jk1/Gradle-License-Report#93]
It'd be nice if the plugin's tasks show up when executing `gradlew tasks`. At the moment, that command doesn't show the one and only task `generateLicenseReport` in the output. Having the task listed there is useful if you happen to forget the task name. You can look it up directly from this list. Note that the task name will show if you run `gradlew tasks --all`, which can be a very large list and will include tasks from all subprojects.

Ideally, I think this task should be listed under the group **Reporting tasks**. If you apply Gradle's built-in plugin such as: buildDashboard, project-report, etc. they are currently listed under that group name.

I think it's a matter of updating the following file and using the constructor to call `setDescription` and `setGroup` methods.

Gradle-License-Report/src/main/groovy/com/github/jk1/license/ReportTask.groovy

**Comment by jk1** [comment]
Released in the scope of 1.2
